name: Spectral OpenAPI Lint

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  spectral-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Spectral CLI
        run: npm install -g @stoplight/spectral-cli
      - name: Run Spectral lint for OpenAPI
        run: spectral lint "./openapi.yaml" --verbose
